apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: bastion.vuong.com.hpemsp.local:5000/myproject/mongo:6.0.2-focal  #mongo:6.0.2-focal
          ports:
            - containerPort: 27017
